// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_RQLvVWPFrHNFB7bFF7t7GJFh2Zx4N9I',
    appId: '1:699659381689:web:4b1e2abee5404bd703e468',
    messagingSenderId: '699659381689',
    projectId: 'naily-app-47fde',
    authDomain: 'naily-app-47fde.firebaseapp.com',
    storageBucket: 'naily-app-47fde.firebasestorage.app',
    measurementId: 'G-YNBK6FTJ5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChKQFE3XreE6vDojzgDl2L3NIZRkji3gM',
    appId: '1:699659381689:android:8f443e59e302cf5d03e468',
    messagingSenderId: '699659381689',
    projectId: 'naily-app-47fde',
    storageBucket: 'naily-app-47fde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrUEgLH4pXbAJPW8IgOLSiVUY5n1sAy9A',
    appId: '1:699659381689:ios:34cbd7a0af03293703e468',
    messagingSenderId: '699659381689',
    projectId: 'naily-app-47fde',
    storageBucket: 'naily-app-47fde.firebasestorage.app',
    iosBundleId: 'com.example.nailyApp',
  );
}
